Repository LikelionUniv/LikelionUniv_Frontend_University, pull requests merged in 2024-06, with the labels that each got.

#76 해커톤 랜딩 페이지 기본 구조도 세팅
  src/pages/landing/LandingPage.tsx
  src/pages/landing/components/hakathon/HakathonLanding.tsx
  src/styles/Layout.ts
Labels: 💄 Design

#77 해커톤 랜딩페이지 안내 컴포넌트 구현
  docs/react-query.md
  package-lock.json
  package.json
  src/api/auth/auth.ts
  src/atoms/HackathonGuide.ts
  src/components/text/Typography.tsx
  src/img/landing/hackathon_1st.svg
  src/img/landing/hackathon_1st_place.svg
  src/img/landing/hackathon_2nd.svg
  src/img/landing/hackathon_2nd_place.svg
  src/img/landing/hackathon_3rd.svg
  src/img/landing/hackathon_3rd_place.svg
  src/img/landing/hackathon_3rd_place2.svg
  src/img/landing/hackathon_arrow.svg
  src/img/landing/hackathon_awards.svg
  src/img/landing/hackathon_guide.svg
  src/img/landing/hackathon_union.svg
  src/index.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/landing/components/hackathon/GuideLine.tsx
  src/pages/landing/components/hackathon/HackathonAwards.tsx
  src/pages/landing/components/hackathon/HackathonAwardsEx.tsx
  src/pages/landing/components/hackathon/HackathonContent.tsx
  src/pages/landing/components/hackathon/HackathonGuide.tsx
  src/pages/landing/components/hackathon/HackathonLanding.tsx
  src/pages/landing/components/hackathon/HackathonNav.tsx
  src/pages/landing/components/hackathon/HackathonSchedule.tsx
  src/pages/landing/components/hackathon/HackathonTimeLine.tsx
  src/pages/project/Detail/DeveloperInfo.tsx
  src/pages/project/Detail/ProjectDetail.tsx
  src/pages/project/components/Header.tsx
  src/pages/project/components/ProjectList.tsx
  src/pages/univ/components/UnivHeader.tsx
  src/query/delete/useDeleteProject.ts
  src/query/get/useGetLocationUniv.ts
  src/query/get/useGetProjectDetail.ts
  src/query/get/useGetUnivList.ts
  src/query/patch/usePatchProjectUpdate.ts
  src/query/post/usePostProjectRegister.ts
  src/styles/HackGuideLine.ts
  src/styles/Layout.ts
Labels: ✨ Feature, 💄 Design

#79 반응형 화면 수상작 overflow 수정
  src/pages/landing/components/hackathon/HackathonAwardsEx.tsx
  src/styles/HackGuideLine.ts
Labels: 🐛 BugFix, 💄 Design

#82 해커톤 타임라인 글자 추가
  src/pages/landing/components/hackathon/HackathonContent.tsx
Labels: ✨ Feature, 💄 Design

#83 해커톤 신청 렌더링 페이지 구현
  package-lock.json
  package.json
  src/img/landing/Arrow_Upright.png
  src/img/landing/Longrightarrow_b.png
  src/img/landing/bulb.png
  src/img/landing/check_g.png
  src/img/landing/check_o.png
  src/img/landing/check_r.png
  src/img/landing/detailBackground.png
  src/img/landing/footprint.png
  src/img/landing/growl_to_world.png
  src/img/landing/info.png
  src/img/landing/longrightarrow_s.png
  src/img/landing/notice.png
  src/img/landing/prize1.png
  src/img/landing/prize1_w.png
  src/img/landing/prize2.png
  src/img/landing/prize2_w.png
  src/img/landing/prize3.png
  src/img/landing/prize3_w.png
  src/img/landing/sponsor/logo1.png
  src/img/landing/sponsor/logo10.png
  src/img/landing/sponsor/logo11.png
  src/img/landing/sponsor/logo12.png
  src/img/landing/sponsor/logo2.png
  src/img/landing/sponsor/logo3.png
  src/img/landing/sponsor/logo4.png
  src/img/landing/sponsor/logo5.png
  src/img/landing/sponsor/logo6.png
  src/img/landing/sponsor/logo7.png
  src/img/landing/sponsor/logo8.png
  src/img/landing/sponsor/logo9.png
  src/img/landing/title.png
  src/img/landing/two_check.png
  src/pages/landing/components/hackathon/Detail.tsx
  src/pages/landing/components/hackathon/HackathonLanding.tsx
  src/pages/landing/components/hackathon/HackathonPart.tsx
  src/pages/landing/components/hackathon/HackathonPrize.tsx
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
  src/pages/landing/components/hackathon/HackathonTimer.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
  src/pages/landing/components/hackathon/More.tsx
  src/pages/landing/components/hackathon/Prize.tsx
  src/pages/landing/components/hackathon/TimeInfo.tsx
  src/styles/HackGuideLine.ts
  src/styles/Layout.ts
Labels: ✨ Feature, 💄 Design

#85 후원사 로고, 순서, url 수정
  src/img/landing/sponsor/logo1.png
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
Labels: 💄 Design

#87 fix: detail BTN navigate 수정
  src/pages/landing/components/hackathon/Detail.tsx
Labels: ✨ Feature, 💄 Design
