Repository LikelionUniv/LikelionUniv_Frontend_University, pull requests merged in 2024-07, with the labels that each got.

#93 Feat/issue #73
  package-lock.json
  package.json
  src/Router.tsx
  src/components/application/AddHypen.tsx
  src/components/application/ApplicationForm.tsx
  src/components/application/ApplicationModify.tsx
  src/components/application/ApplicationSchema.ts
  src/components/application/ApplicationStyle.ts
  src/components/application/CompleteApplication.tsx
  src/components/application/CompleteApplicationStyle.ts
  src/components/application/Dropdown.tsx
  src/components/application/DropdownStyle.ts
  src/components/application/MobileDropdownStyle.ts
  src/components/application/SelectedOption.tsx
  src/components/application/SelectedOptionStyle.ts
  src/components/application/modal/ApplicationModal.tsx
  src/components/application/modal/ApplicationModalStyle.ts
  src/components/mypage/Hackathons/ApplyList.tsx
  src/components/mypage/Hackathons/ApplySelect.tsx
  src/components/mypage/Hackathons/ApplytListStyle.ts
  src/img/application/Cancel16.svg
  src/img/application/checkboxChecked16.svg
  src/img/application/checkboxNotChecked16.svg
  src/img/application/checked16.svg
  src/img/application/chervron_left.svg
  src/img/application/modarringMobile.svg
  src/img/application/not_checked16.svg
  src/img/application/radioChecked.svg
  src/img/application/radioNotChecked.svg
  src/pages/mypage/components/EmptyBox.tsx
  src/pages/mypage/components/UserPostSelect.tsx
  src/routes/HackathonsApplicationPage.tsx
  src/routes/HackathonsModifyPage.tsx
Labels: ✨ Feature, 💄 Design

#95 Fix: 해커톤 수상작 이름 수정
  src/pages/landing/components/hackathon/HackathonAwardsEx.tsx
Labels: 🐛 BugFix, 💄 Design

#98 Design/hackaton landing fix
  src/api/auth/auth.ts
  src/pages/landing/components/hackathon/Detail.tsx
  src/pages/landing/components/hackathon/HackathonPart.tsx
  src/pages/landing/components/hackathon/HackathonPrize.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
  src/pages/landing/components/hackathon/More.tsx
Labels: 🐛 BugFix, 💄 Design

#100 Fix/hackathon login nav fix
  src/api/auth/auth.ts
  src/pages/landing/components/Information.style.ts
  src/pages/landing/components/hackathon/Detail.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
  src/pages/landing/components/hackathon/More.tsx
  src/pages/login/components/Redirect.tsx
Labels: 🐛 BugFix, 💄 Design

#102 해커톤 랜딩페이지 타임라인 글자 수정
  src/pages/landing/components/hackathon/HackathonContent.tsx
  src/pages/landing/components/hackathon/HackathonTimeLine.tsx
Labels: 🐛 BugFix, 💄 Design

#104 Fix/hackathon sponsor url fix
  src/img/landing/sponsor/logo9.png
  src/pages/landing/components/hackathon/Detail.tsx
  src/pages/landing/components/hackathon/HackathonPrize.tsx
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
Labels: 💄 Design

#107 design: prize 반응형 css 수정
  src/pages/landing/components/hackathon/HackathonPrize.tsx
  src/pages/landing/components/hackathon/More.tsx
  src/pages/landing/components/hackathon/Prize.tsx
Labels: 💄 Design

#110 design: mainInfo 그라데이션 수정
  src/pages/landing/components/hackathon/HackathonPart.tsx
  src/pages/landing/components/hackathon/HackathonTimer.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
  src/pages/landing/components/hackathon/TimeInfo.tsx
Labels: 💄 Design

#111 Fix: 해커톤 신청 수정폼 디자인 오류 수정
  src/components/application/ApplicationModify.tsx
  src/components/application/modal/ApplicationModal.tsx
  src/components/application/modal/ApplicationModalStyle.ts
Labels: 💄 Design

#113 design: 이미지 svg 로 수정완료
  src/img/landing/Prize1.svg
  src/img/landing/Prize1_w.svg
  src/img/landing/Prize2.svg
  src/img/landing/Prize2_w.svg
  src/img/landing/Prize3.svg
  src/img/landing/Prize3_w.svg
  src/img/landing/info.png
  src/img/landing/info.svg
  src/img/landing/prize1.png
  src/img/landing/prize1_w.png
  src/img/landing/prize2.png
  src/img/landing/prize2_w.png
  src/img/landing/prize3.png
  src/img/landing/prize3_w.png
  src/img/landing/sponsor/logo1.png
  src/img/landing/sponsor/logo1.svg
  src/img/landing/sponsor/logo10.png
  src/img/landing/sponsor/logo10.svg
  src/img/landing/sponsor/logo11.png
  src/img/landing/sponsor/logo11.svg
  src/img/landing/sponsor/logo12.png
  src/img/landing/sponsor/logo12.svg
  src/img/landing/sponsor/logo2.png
  src/img/landing/sponsor/logo2.svg
  src/img/landing/sponsor/logo3.png
  src/img/landing/sponsor/logo3.svg
  src/img/landing/sponsor/logo4.png
  src/img/landing/sponsor/logo4.svg
  src/img/landing/sponsor/logo5.png
  src/img/landing/sponsor/logo5.svg
  src/img/landing/sponsor/logo6.png
  src/img/landing/sponsor/logo6.svg
  src/img/landing/sponsor/logo7.png
  src/img/landing/sponsor/logo7.svg
  src/img/landing/sponsor/logo8.png
  src/img/landing/sponsor/logo8.svg
  src/img/landing/sponsor/logo9.png
  src/img/landing/sponsor/logo9.svg
  src/img/landing/title.png
  src/img/landing/title.svg
  src/pages/landing/components/hackathon/HackathonPrize.tsx
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
Labels: 💄 Design

#117 fix: sponsor Logo 오류 수정
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
Labels: 🐛 BugFix

#119 Design/hackathon partbtn css fix
  src/pages/landing/components/hackathon/Detail.tsx
  src/pages/landing/components/hackathon/HackathonPart.tsx
  src/pages/landing/components/hackathon/HackathonSponsor.tsx
  src/pages/landing/components/hackathon/HackathonTimer.tsx
  src/pages/landing/components/hackathon/MainInfo.tsx
  src/pages/landing/components/hackathon/More.tsx
Labels: 💄 Design

#124 07월 14일 해당 날짜 지날 시 타이머 내용 및 타이머 바뀌도록 수정
  package-lock.json
  package.json
  src/Router.tsx
  src/atoms/HackathonDeadline.ts
  src/pages/landing/components/hackathon/HackathonPart.tsx
  src/pages/landing/components/hackathon/HackathonTimer.tsx
  src/pages/landing/components/hackathon/TimeInfo.tsx
Labels: ✨ Feature, 💄 Design, ♻️ Refactoring
